In [2]:
import pandas as pd

# Create a pandas DataFrame using the employee data provided
data = {
    'EmployeeID': [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    'Name': ['Sarah', 'Michael', 'Jennifer', 'David', 'Lisa', 'James', 'Emma', 'Robert', 'Sophia', 'William'],
    'Department': ['Engineering', 'Sales', 'Marketing', 'Engineering', 'HR', 'Sales', 'Engineering', 'Marketing', 'Sales', 'HR'],
    'Salary': [85000, 62000, 71000, 92000, 58000, 68000, 78000, 75000, 65000, 60000],
    'Performance Score': [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    'Years of Service': [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}
df = pd.DataFrame(data)

In [3]:
df_selected = df[['Name', 'Department', 'Salary']]
df_selected

       Name   Department  Salary
0     Sarah  Engineering   85000
1   Michael        Sales   62000
2  Jennifer    Marketing   71000
3     David  Engineering   92000
4      Lisa           HR   58000
5     James        Sales   68000
6      Emma  Engineering   78000
7    Robert    Marketing   75000
8    Sophia        Sales   65000
9   William           HR   60000

In [4]:
emp_at_5 = df.iloc[5]
emp_at_5

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 5, dtype: object

In [8]:
emp_at_208 = df.loc[df['EmployeeID'] == 208]
emp_at_208

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
7         208  Robert  Marketing   75000                  4                 5

In [9]:
emp_engg = df[df['Department'] == 'Engineering']
emp_engg

   EmployeeID   Name   Department  Salary  Performance Score  Years of Service
0         201  Sarah  Engineering   85000                  4                 5
3         204  David  Engineering   92000                  5                 8
6         207   Emma  Engineering   78000                  3                 2

In [10]:
emp_highsal = df[df['Salary'] > 70000]
emp_highsal

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
0,201,Sarah,Engineering,85000,4,5
2,203,Jennifer,Marketing,71000,5,7
3,204,David,Engineering,92000,5,8
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5

In [11]:
sales_highperformance = df[(df['Department'] == 'Sales') & (df['Performance Score'] >= 4)]
sales_highperformance

   EmployeeID    Name Department  Salary  Performance Score  Years of Service
5         206   James      Sales   68000                  4                 6
8         209  Sophia      Sales   65000                  5                 4

In [12]:
df_Salarydesc = df.sort_values(by='Salary',ascending=False)
df_Salarydesc

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4

In [13]:
df_sort_asc_Desc =  df.sort_values(by=['Department','Salary'],ascending=[True,False])
df_sort_asc_Desc

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
3,204,David,Engineering,92000,5,8
0,201,Sarah,Engineering,85000,4,5
6,207,Emma,Engineering,78000,3,2
9,210,William,HR,60000,3,3
4,205,Lisa,HR,58000,4,4
7,208,Robert,Marketing,75000,4,5
2,203,Jennifer,Marketing,71000,5,7
5,206,James,Sales,68000,4,6
8,209,Sophia,Sales,65000,5,4
1,202,Michael,Sales,62000,3,3